#!/bin/bash

_term() {
  7dtd-shutdown
}

trap _term SIGTERM

./7DaysToDieServer.x86_64 \
  -logfile /data/logfile.txt \
  -configfile=$CONFIG_FILE \
  -quit \
  -batchmode \
  -nographics \
  -dedicated &

child=$!
wait "$child"
