version: "3.3"
services:
  image:
    build: .
    image: dtlandry/7daystodie
    tty: true
    stdin_open: true
    environment:
      STEAMCMD_SKIP: "true"
      USER_UID: "1001"
      USER_GID: "1001"
    ports:
      - "26900-26902:26900-26902"
      - "26900-26902:26900-26902/udp"
    volumes:
      - ./data:/data
